name       : font-iosevka-ttf
version    : 26.0.1
release    : 38
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v26.0.1/ttf-iosevka-26.0.1.zip : e32271df14bd7226a961fae6e1ff5b0b8f480f19a599c9fefb6fc7195f5ca4b8
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
