name       : font-iosevka-ttf
version    : 2.0.1
release    : 3
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v2.0.1/01-iosevka-2.0.1.zip : 94c548d79f3db4504f9e804a11845479b03d16a2c80edc5818d1ed79cae6638f
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
