name       : font-iosevka-ttf
version    : 15.1.0
release    : 13
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v15.1.0/ttf-iosevka-15.1.0.zip : d1f83b08d78012c957629d72c13f14ddfd3c407b250201a142012dac290240b7
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
