name       : font-iosevka-ttf
version    : 22.0.2
release    : 30
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v22.0.2/ttf-iosevka-22.0.2.zip : 12a30c76610bcdaf7c9a4e82e2765b5c3134d08bb797eb6f795290a3d5e0e0da
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
