name       : font-iosevka-ttf
version    : 16.3.4
release    : 22
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v16.3.4/ttf-iosevka-16.3.4.zip : 2be6c6ed3264377e3b2cbb88db4b7ab572ae07f960f7c9c4083cb248a4ddf825
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
