name       : font-iosevka-ttf
version    : 22.1.2
release    : 31
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v22.1.2/ttf-iosevka-22.1.2.zip : 48444fb05b9f5db7d6fcbeddb00745c3cb61a3b92c83562acaa3425fa625b383
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
