name       : font-iosevka-ttf
version    : 26.2.1
release    : 39
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v26.2.1/ttf-iosevka-26.2.1.zip : 4145d68f681ec7c365eb5a21cb84f553dc86ccb65b3261535f37b025fa735a27
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
