name       : font-iosevka-ttf
version    : 2.3.3
release    : 6
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v2.3.3/01-iosevka-2.3.3.zip : cc8de3ca577b8a1d4947dccdfff8205042e479f0223a574de35927e13f506f90
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
