name       : font-iosevka-ttf
version    : 25.1.1
release    : 37
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v25.1.1/ttf-iosevka-25.1.1.zip : c8f7218a0174aeb12f4633292248946894bf78a734392c427268a49b417ca497
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
