name       : font-iosevka-ttf
version    : 15.5.0
release    : 15
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v15.5.0/ttf-iosevka-15.5.0.zip : 541c5b7bc8794585615c70d251c8dde26f74da80a78ccbc6468c755746f104f3
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
