name       : font-iosevka-ttf
version    : 11.2.6
release    : 8
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v11.2.6/ttf-iosevka-11.2.6.zip : 03145d713241e4d9c27beb7bd6e2574e433155676e0346443cad5802fc42d23f
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
