name       : font-iosevka-ttf
version    : 16.5.0
release    : 24
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v16.5.0/ttf-iosevka-16.5.0.zip : 141390146e4da30ffcaa786c55757dbecb0b327cebc4e9b1c416cdd20029d092
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
