name       : font-iosevka-ttf
version    : 2.2.1
release    : 5
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v2.2.1/01-iosevka-2.2.1.zip : 0ec450cd3c5e6dc22cc2194e67a1184339eaedacdd485a79a839ee530d057d56
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
