name       : font-iosevka-ttf
version    : 23.0.0
release    : 32
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v23.0.0/ttf-iosevka-23.0.0.zip : 471cca71244a1f1407465938b679fa532ee6a17c08b3d96e95028e8582f76bb9
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
