name       : font-iosevka-ttf
version    : 16.8.0
release    : 26
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v16.8.0/ttf-iosevka-16.8.0.zip : 108c7fd4b9a0c3fd8a227a093a5141d55103fc49a9f4ae9ccf51e328cc299162
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
