name       : font-iosevka-ttf
version    : 11.2.7
release    : 9
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v11.2.7/ttf-iosevka-11.2.7.zip : 1fbb962c4e9cf45e2ccedde3884aca502828d34ef3a43dd2e56e4604bc2c311e
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
