name       : font-iosevka-ttf
version    : 15.6.0
release    : 16
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v15.6.0/ttf-iosevka-15.6.0.zip : 107dfd61125ddb6b440d3c4c86233c4afbc0cfc9045cb2650d691a888c6ab3ee
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
