name       : font-iosevka-ttf
version    : 24.1.4
release    : 35
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v24.1.4/ttf-iosevka-24.1.4.zip : bc8d5baee26c87a7e37beb6ea1fc8ddabdc308e9515a448080dd47e7a475d1c5
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
