name       : font-iosevka-ttf
version    : 26.3.2
release    : 41
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v26.3.2/ttf-iosevka-26.3.2.zip : 681fec18f0c76a75b46d04b57717d5b0a0d86f657fc9b04e2b486a8479901c21
homepage   : https://typeof.net/Iosevka
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
