name       : font-iosevka-ttf
version    : 15.4.2
release    : 14
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v15.4.2/ttf-iosevka-15.4.2.zip : 22441b9e7f09410ca4c2fc1cea7ebec0e318d09b81190b02cca30851da623e97
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
