name       : font-iosevka-ttf
version    : 2.0.0
release    : 2
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v2.0.0/01-iosevka-2.0.0.zip : a078ed67f5c83752bead30c124ca6359e64bd6ca15a0aef7f22c0b455b08a03c
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
