name       : font-iosevka-ttf
version    : 1.14.3
release    : 1
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v1.14.3/01-iosevka-1.14.3.zip : 47a7cd15ae9b146fa837fcb30557b78657a0ce089781f9903faa395cd4f01d54
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
