name       : font-iosevka-ttf
version    : 17.0.1
release    : 28
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v17.0.1/ttf-iosevka-17.0.1.zip : e040899eedc851847c83db8c82c5ba92725b144f2bb704893c9dd502219168ea
license    : OFL-1.1
component  : desktop.font
summary    : Slender typeface for code, from code (default shape)
description: |
    Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.
install    : |
    install -D -m00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
